import command
import functions

from telegram.ext import Updater, CommandHandler, MessageHandler, Filters


def main():
    print('\nHellolilybot is running....')

    # define the updater
    updater = Updater(token='1712133560:AAGICLPJ2NeM2NC52Jdtwy_29RF6X6aTpAg', use_context=True)

    # define the dispatcher
    dp = updater.dispatcher

    # commands
    dp.add_handler(CommandHandler(('start', 'help'), command.command_help))
    dp.add_handler(CommandHandler(('covidglobal'), command.command_covidglobal))

    dp.add_handler(CommandHandler(('afghanistan'), command.command_0))
    dp.add_handler(CommandHandler(('albania'), command.command_1))
    dp.add_handler(CommandHandler(('algeria'), command.command_2))
    dp.add_handler(CommandHandler(('andorra'), command.command_3))
    dp.add_handler(CommandHandler(('angola'), command.command_4))
    dp.add_handler(CommandHandler(('antiguaandbarbuda'), command.command_5))
    dp.add_handler(CommandHandler(('argentina'), command.command_6))
    dp.add_handler(CommandHandler(('armenia'), command.command_7))
    dp.add_handler(CommandHandler(('australia'), command.command_8))
    dp.add_handler(CommandHandler(('austria'), command.command_9))
    dp.add_handler(CommandHandler(('azerbaijan'), command.command_10))
    dp.add_handler(CommandHandler(('bahamas'), command.command_11))
    dp.add_handler(CommandHandler(('bahrain'), command.command_12))
    dp.add_handler(CommandHandler(('bangladesh'), command.command_13))
    dp.add_handler(CommandHandler(('barbados'), command.command_14))
    dp.add_handler(CommandHandler(('belarus'), command.command_15))
    dp.add_handler(CommandHandler(('belgium'), command.command_16))
    dp.add_handler(CommandHandler(('belize'), command.command_17))
    dp.add_handler(CommandHandler(('benin'), command.command_18))
    dp.add_handler(CommandHandler(('bhutan'), command.command_19))
    dp.add_handler(CommandHandler(('bolivia'), command.command_20))
    dp.add_handler(CommandHandler(('bosniaandherzegovina'), command.command_21))
    dp.add_handler(CommandHandler(('botswana'), command.command_22))
    dp.add_handler(CommandHandler(('brazil'), command.command_23))
    dp.add_handler(CommandHandler(('brunei'), command.command_24))
    dp.add_handler(CommandHandler(('bulgaria'), command.command_25))
    dp.add_handler(CommandHandler(('burkinafaso'), command.command_26))
    dp.add_handler(CommandHandler(('burundi'), command.command_27))
    dp.add_handler(CommandHandler(('cambodia'), command.command_28))
    dp.add_handler(CommandHandler(('cameroon'), command.command_29))
    dp.add_handler(CommandHandler(('canada'), command.command_30))
    dp.add_handler(CommandHandler(('capeverde'), command.command_31))
    dp.add_handler(CommandHandler(('centralafricanrepublic'), command.command_32))
    dp.add_handler(CommandHandler(('chad'), command.command_33))
    dp.add_handler(CommandHandler(('chile'), command.command_34))
    dp.add_handler(CommandHandler(('china'), command.command_35))
    dp.add_handler(CommandHandler(('colombia'), command.command_36))
    dp.add_handler(CommandHandler(('comoros'), command.command_37))
    dp.add_handler(CommandHandler(('congobrazzaville'), command.command_38))
    dp.add_handler(CommandHandler(('congokinshasa'), command.command_39))
    dp.add_handler(CommandHandler(('costarica'), command.command_40))
    dp.add_handler(CommandHandler(('croatia'), command.command_41))
    dp.add_handler(CommandHandler(('cuba'), command.command_42))
    dp.add_handler(CommandHandler(('cyprus'), command.command_43))
    dp.add_handler(CommandHandler(('czechrepublic'), command.command_44))
    dp.add_handler(CommandHandler(('cotedivoire'), command.command_45))
    dp.add_handler(CommandHandler(('denmark'), command.command_46))
    dp.add_handler(CommandHandler(('djibouti'), command.command_47))
    dp.add_handler(CommandHandler(('dominica'), command.command_48))
    dp.add_handler(CommandHandler(('dominicanrepublic'), command.command_49))
    dp.add_handler(CommandHandler(('ecuador'), command.command_50))
    dp.add_handler(CommandHandler(('egypt'), command.command_51))
    dp.add_handler(CommandHandler(('elsalvador'), command.command_52))
    dp.add_handler(CommandHandler(('equatorialguinea'), command.command_53))
    dp.add_handler(CommandHandler(('eritrea'), command.command_54))
    dp.add_handler(CommandHandler(('estonia'), command.command_55))
    dp.add_handler(CommandHandler(('ethiopia'), command.command_56))
    dp.add_handler(CommandHandler(('fiji'), command.command_57))
    dp.add_handler(CommandHandler(('finland'), command.command_58))
    dp.add_handler(CommandHandler(('france'), command.command_59))
    dp.add_handler(CommandHandler(('gabon'), command.command_60))
    dp.add_handler(CommandHandler(('gambia'), command.command_61))
    dp.add_handler(CommandHandler(('georgia'), command.command_62))
    dp.add_handler(CommandHandler(('germany'), command.command_63))
    dp.add_handler(CommandHandler(('ghana'), command.command_64))
    dp.add_handler(CommandHandler(('greece'), command.command_65))
    dp.add_handler(CommandHandler(('grenada'), command.command_66))
    dp.add_handler(CommandHandler(('guatemala'), command.command_67))
    dp.add_handler(CommandHandler(('guinea'), command.command_68))
    dp.add_handler(CommandHandler(('guineabissau'), command.command_69))
    dp.add_handler(CommandHandler(('guyana'), command.command_70))
    dp.add_handler(CommandHandler(('haiti'), command.command_71))
    dp.add_handler(CommandHandler(('vaticancity'), command.command_72))
    dp.add_handler(CommandHandler(('honduras'), command.command_73))
    dp.add_handler(CommandHandler(('hungary'), command.command_74))
    dp.add_handler(CommandHandler(('iceland'), command.command_75))
    dp.add_handler(CommandHandler(('india'), command.command_76))
    dp.add_handler(CommandHandler(('indonesia'), command.command_77))
    dp.add_handler(CommandHandler(('iran'), command.command_78))
    dp.add_handler(CommandHandler(('iraq'), command.command_79))
    dp.add_handler(CommandHandler(('ireland'), command.command_80))
    dp.add_handler(CommandHandler(('israel'), command.command_81))
    dp.add_handler(CommandHandler(('italy'), command.command_82))
    dp.add_handler(CommandHandler(('jamaica'), command.command_83))
    dp.add_handler(CommandHandler(('japan'), command.command_84))
    dp.add_handler(CommandHandler(('jordan'), command.command_85))
    dp.add_handler(CommandHandler(('kazakhstan'), command.command_86))
    dp.add_handler(CommandHandler(('kenya'), command.command_87))
    dp.add_handler(CommandHandler(('southkorea'), command.command_88))
    dp.add_handler(CommandHandler(('kuwait'), command.command_89))
    dp.add_handler(CommandHandler(('kyrgyzstan'), command.command_90))
    dp.add_handler(CommandHandler(('laos'), command.command_91))
    dp.add_handler(CommandHandler(('latvia'), command.command_92))
    dp.add_handler(CommandHandler(('lebanon'), command.command_93))
    dp.add_handler(CommandHandler(('lesotho'), command.command_94))
    dp.add_handler(CommandHandler(('liberia'), command.command_95))
    dp.add_handler(CommandHandler(('libya'), command.command_96))
    dp.add_handler(CommandHandler(('liechtenstein'), command.command_97))
    dp.add_handler(CommandHandler(('lithuania'), command.command_98))
    dp.add_handler(CommandHandler(('luxembourg'), command.command_99))
    dp.add_handler(CommandHandler(('macedonia'), command.command_100))
    dp.add_handler(CommandHandler(('madagascar'), command.command_101))
    dp.add_handler(CommandHandler(('malawi'), command.command_102))
    dp.add_handler(CommandHandler(('malaysia'), command.command_103))
    dp.add_handler(CommandHandler(('maldives'), command.command_104))
    dp.add_handler(CommandHandler(('mali'), command.command_105))
    dp.add_handler(CommandHandler(('malta'), command.command_106))
    dp.add_handler(CommandHandler(('marshallislands'), command.command_107))
    dp.add_handler(CommandHandler(('mauritania'), command.command_108))
    dp.add_handler(CommandHandler(('mauritius'), command.command_109))
    dp.add_handler(CommandHandler(('mexico'), command.command_110))
    dp.add_handler(CommandHandler(('micronesia'), command.command_111))
    dp.add_handler(CommandHandler(('moldova'), command.command_112))
    dp.add_handler(CommandHandler(('monaco'), command.command_113))
    dp.add_handler(CommandHandler(('mongolia'), command.command_114))
    dp.add_handler(CommandHandler(('montenegro'), command.command_115))
    dp.add_handler(CommandHandler(('morocco'), command.command_116))
    dp.add_handler(CommandHandler(('mozambique'), command.command_117))
    dp.add_handler(CommandHandler(('myanmar'), command.command_118))
    dp.add_handler(CommandHandler(('namibia'), command.command_119))
    dp.add_handler(CommandHandler(('nepal'), command.command_120))
    dp.add_handler(CommandHandler(('netherlands'), command.command_121))
    dp.add_handler(CommandHandler(('newzealand'), command.command_122))
    dp.add_handler(CommandHandler(('nicaragua'), command.command_123))
    dp.add_handler(CommandHandler(('niger'), command.command_124))
    dp.add_handler(CommandHandler(('nigeria'), command.command_125))
    dp.add_handler(CommandHandler(('norway'), command.command_126))
    dp.add_handler(CommandHandler(('oman'), command.command_127))
    dp.add_handler(CommandHandler(('pakistan'), command.command_128))
    dp.add_handler(CommandHandler(('palestine'), command.command_129))
    dp.add_handler(CommandHandler(('panama'), command.command_130))
    dp.add_handler(CommandHandler(('papuanewguinea'), command.command_131))
    dp.add_handler(CommandHandler(('paraguay'), command.command_132))
    dp.add_handler(CommandHandler(('peru'), command.command_133))
    dp.add_handler(CommandHandler(('philippines'), command.command_134))
    dp.add_handler(CommandHandler(('poland'), command.command_135))
    dp.add_handler(CommandHandler(('portugal'), command.command_136))
    dp.add_handler(CommandHandler(('qatar'), command.command_137))
    dp.add_handler(CommandHandler(('kosovo'), command.command_138))
    dp.add_handler(CommandHandler(('romania'), command.command_139))
    dp.add_handler(CommandHandler(('russia'), command.command_140))
    dp.add_handler(CommandHandler(('rwanda'), command.command_141))
    dp.add_handler(CommandHandler(('saintkittsandnevis'), command.command_142))
    dp.add_handler(CommandHandler(('saintlucia'), command.command_143))
    dp.add_handler(CommandHandler(('saintvincentandthegrenadines'), command.command_144))
    dp.add_handler(CommandHandler(('samoa'), command.command_145))
    dp.add_handler(CommandHandler(('sanmarino'), command.command_146))
    dp.add_handler(CommandHandler(('saotomeandprincipe'), command.command_147))
    dp.add_handler(CommandHandler(('saudiarabia'), command.command_148))
    dp.add_handler(CommandHandler(('senegal'), command.command_149))
    dp.add_handler(CommandHandler(('serbia'), command.command_150))
    dp.add_handler(CommandHandler(('seychelles'), command.command_151))
    dp.add_handler(CommandHandler(('sierraleone'), command.command_152))
    dp.add_handler(CommandHandler(('singapore'), command.command_153))
    dp.add_handler(CommandHandler(('slovakia'), command.command_154))
    dp.add_handler(CommandHandler(('slovenia'), command.command_155))
    dp.add_handler(CommandHandler(('solomonislands'), command.command_156))
    dp.add_handler(CommandHandler(('somalia'), command.command_157))
    dp.add_handler(CommandHandler(('southafrica'), command.command_158))
    dp.add_handler(CommandHandler(('southsudan'), command.command_159))
    dp.add_handler(CommandHandler(('spain'), command.command_160))
    dp.add_handler(CommandHandler(('srilanka'), command.command_161))
    dp.add_handler(CommandHandler(('sudan'), command.command_162))
    dp.add_handler(CommandHandler(('suriname'), command.command_163))
    dp.add_handler(CommandHandler(('swaziland'), command.command_164))
    dp.add_handler(CommandHandler(('sweden'), command.command_165))
    dp.add_handler(CommandHandler(('switzerland'), command.command_166))
    dp.add_handler(CommandHandler(('syria'), command.command_167))
    dp.add_handler(CommandHandler(('taiwan'), command.command_168))
    dp.add_handler(CommandHandler(('tajikistan'), command.command_169))
    dp.add_handler(CommandHandler(('tanzania'), command.command_170))
    dp.add_handler(CommandHandler(('thailand'), command.command_171))
    dp.add_handler(CommandHandler(('timorleste'), command.command_172))
    dp.add_handler(CommandHandler(('togo'), command.command_173))
    dp.add_handler(CommandHandler(('trinidadandtobago'), command.command_174))
    dp.add_handler(CommandHandler(('tunisia'), command.command_175))
    dp.add_handler(CommandHandler(('turkey'), command.command_176))
    dp.add_handler(CommandHandler(('uganda'), command.command_177))
    dp.add_handler(CommandHandler(('ukraine'), command.command_178))
    dp.add_handler(CommandHandler(('unitedarabemirates'), command.command_179))
    dp.add_handler(CommandHandler(('unitedkingdom'), command.command_180))
    dp.add_handler(CommandHandler(('unitedstatesofamerica'), command.command_181))
    dp.add_handler(CommandHandler(('uruguay'), command.command_182))
    dp.add_handler(CommandHandler(('uzbekistan'), command.command_183))
    dp.add_handler(CommandHandler(('vanuatu'), command.command_184))
    dp.add_handler(CommandHandler(('venezuela'), command.command_185))
    dp.add_handler(CommandHandler(('vietnam'), command.command_186))
    dp.add_handler(CommandHandler(('yemen'), command.command_187))
    dp.add_handler(CommandHandler(('zambia'), command.command_188))
    dp.add_handler(CommandHandler(('zimbabwe'), command.command_189))

    # corona_summary_handler = CommandHandler('covid', summary)
    # dispatcher.add_handler(corona_summary_handler)

    # handling messages
    dp.add_handler(MessageHandler(Filters.all, functions.echo_all))


    # handling errors
    # dp.add_error_handler(error)

    updater.start_polling()  #starts the bot, the bot begins
    updater.idle() #commands is used to block the script until the user sends a new command to break it from python script


if __name__ == '__main__':
    main()