
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEDIVIDE EQUALS LPAREN MINUS NAME NUMBER PLUS RPAREN TIMESstatement : NAME EQUALS expressionstatement : expressionexpression   : expression PLUS expression\n                    | expression MINUS expression\n                    | expression TIMES expression\n                    | expression DIVIDE expression\n    expression : LPAREN expression RPARENexpression : NUMBERexpression : NAME'
    
_lr_action_items = {'NAME':([0,4,6,7,8,9,10,],[2,12,12,12,12,12,12,]),'LPAREN':([0,4,6,7,8,9,10,],[4,4,4,4,4,4,4,]),'NUMBER':([0,4,6,7,8,9,10,],[5,5,5,5,5,5,5,]),'$end':([1,2,3,5,12,13,14,15,16,17,18,],[0,-9,-2,-8,-9,-1,-3,-4,-5,-6,-7,]),'EQUALS':([2,],[6,]),'PLUS':([2,3,5,11,12,13,14,15,16,17,18,],[-9,7,-8,7,-9,7,-3,-4,-5,-6,-7,]),'MINUS':([2,3,5,11,12,13,14,15,16,17,18,],[-9,8,-8,8,-9,8,-3,-4,-5,-6,-7,]),'TIMES':([2,3,5,11,12,13,14,15,16,17,18,],[-9,9,-8,9,-9,9,9,9,-5,-6,-7,]),'DIVIDE':([2,3,5,11,12,13,14,15,16,17,18,],[-9,10,-8,10,-9,10,10,10,-5,-6,-7,]),'RPAREN':([5,11,12,14,15,16,17,18,],[-8,18,-9,-3,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,6,7,8,9,10,],[3,11,13,14,15,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','mainCompiler.py',59),
  ('statement -> expression','statement',1,'p_statement_expr','mainCompiler.py',64),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','mainCompiler.py',69),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','mainCompiler.py',70),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','mainCompiler.py',71),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','mainCompiler.py',72),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','mainCompiler.py',85),
  ('expression -> NUMBER','expression',1,'p_expression_number','mainCompiler.py',90),
  ('expression -> NAME','expression',1,'p_expression_name','mainCompiler.py',96),
]
